enable_auto_init_connections: true 
log_file: log/messagebus-client.log

user: guest
passwd: guest
receipt_wait_timeout_ms: 1500
conn_lifetime_sec: 300

clusters:
  -
    name: orders-messagebus-cluster
    producer_address: "localhost:61613"
    consumer_address: "localhost:8081"
    destinations:
      - jms.queue.testQueue1
      - jms.queue.testQueue2
      - jms.topic.testTopic1
